package no.ccat.service;

import no.ccat.model.ConceptDenormalized;
import org.springframework.data.elasticsearch.annotations.Query;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.util.List;

@RepositoryRestResource(itemResourceRel = "concept", collectionResourceRel = "concepts", exported = false)
public interface ConceptDenormalizedRepository
    extends ElasticsearchRepository<ConceptDenormalized, String> {

    // this is used later if we have synchronization of a set at once, so we can delete
    // the items not found in the new set version
    // List<ConceptDenormalized> findByHarvestSourceUri(String harvestSourceUri);

    //todo there is something wrong with the autogenerated query. (0 items returned)
    // With this annotation, the query works
    @Query("{\"term\":{\"identifier\":\"?0\"}}")
    ConceptDenormalized findByIdentifier(String identifier);

}
