
# Rule 6: Dataet has title

prefix dcat:  <http://www.w3.org/ns/dcat#> 
prefix dct:   <http://purl.org/dc/terms/> 
SELECT ?ruleId ?ruleDescription ?resourceId ?status
WHERE 
{
      ?resourceId a dcat:Dataset .
      OPTIONAL {?resourceId dct:title ?title .}
      BIND (6 as ?ruleId) 
      BIND (("Dataset has title") as ?ruleDescription) 
      BIND (BOUND(?title) as ?status)
}     
