
# Rule 5: Dataet has description

prefix dcat:  <http://www.w3.org/ns/dcat#> 
prefix dct:   <http://purl.org/dc/terms/> 
SELECT ?ruleId ?ruleDescription ?resourceId ?status
WHERE 
{
      ?resourceId a dcat:Dataset .
      OPTIONAL {?resourceId dct:description ?description .}
      BIND (5 as ?ruleId) 
      BIND (("Dataset has description") as ?ruleDescription) 
      BIND (BOUND(?description) as ?status)
}     
