export const PROVENANCE_REQUEST = 'PROVENANCE_REQUEST';
export const PROVENANCE_SUCCESS = 'PROVENANCE_SUCCESS';
export const PROVENANCE_FAILURE = 'PROVENANCE_FAILURE';

export const FREQUENCY_REQUEST = 'FREQUENCY_REQUEST';
export const FREQUENCY_SUCCESS = 'FREQUENCY_SUCCESS';
export const FREQUENCY_FAILURE = 'FREQUENCY_FAILURE';

export const REFERENCEDATASETS_REQUEST = 'REFERENCEDATASETS_REQUEST';
export const REFERENCEDATASETS_SUCCESS = 'REFERENCEDATASETS_SUCCESS';
export const REFERENCEDATASETS_FAILURE = 'REFERENCEDATASETS_FAILURE';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const CATALOGS_REQUEST = 'CATALOGS_REQUEST';
export const CATALOGS_SUCCESS = 'CATALOGS_SUCCESS';
export const CATALOGS_FAILURE = 'CATALOGS_FAILURE';

export const PUBLISHDATASET = 'PUBLISHDATASET';

export const DATASET_LAST_SAVED = 'DATASET_LAST_SAVED';
