export const DATASET_REQUEST = 'DATASET_REQUEST';
export const DATASET_SUCCESS = 'DATASET_SUCCESS';
export const DATASET_FAILURE = 'DATASET_FAILURE';

export const HELPTEXTS_REQUEST = 'HELPTEXTS_REQUEST';
export const HELPTEXTS_SUCCESS = 'HELPTEXTS_SUCCESS';
export const HELPTEXTS_FAILURE = 'HELPTEXTS_FAILURE';
