prefix apf: <http://jena.apache.org/ARQ/property#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dct:  <https://purl.org/dc/terms/>
prefix : <http://data.brreg.no/vocab/temp/> 
prefix foaf:  <http://xmlns.com/foaf/0.1/>
prefix adms: <http://www.w3.org/ns/adms#> 
prefix dct: <http://purl.org/dc/terms/>
prefix time: <http://www.w3.org/TR/owl-time/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

construct {
    ?id dct:temporal _:p .
        _:p a dct:PeriodOfTime .
        _:p time:hasBeginning _:s .
            _:s a time:Instant .
            _:s time:inXSDDateTime ?xsdfrom .
        _:p time:hasEnd _:e .
            _:e a time:Instant .
	        _:e time:inXSDDateTime ?xsdto . 


}

WHERE {
  
     # period
     ?id :fra ?from .
     BIND(strbefore( ?from, "." ) as ?day1)
     BIND(strbefore(strafter(?from, "."), ".") as ?month1)
     BIND(strafter(strafter(?from, "."), ".") as ?year1)
     BIND(xsd:date(concat(?year1, "-" ,?month1, "-" , ?day1)) as ?fromDate)
     ?id :til ?to .
     BIND(strbefore( ?to, "." ) as ?day2)
     BIND(strbefore(strafter(?to, "."), ".") as ?month2)
     BIND(strafter(strafter(?to, "."), ".") as ?year2)
     BIND(xsd:date(concat(?year2, "-", ?month2, "-", ?day2)) as ?toDate)
     
     
     BIND(xsd:dateTime(concat( str(?fromDate) , "T00:00:00Z")) as ?xsdfrom)
     BIND(xsd:dateTime(concat(str(?toDate), "T00:00:00Z")) as ?xsdto)   
  
}
