prefix apf: <http://jena.apache.org/ARQ/property#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dct:  <https://purl.org/dc/terms/>
prefix : <http://data.brreg.no/vocab/temp/> 
prefix foaf:  <http://xmlns.com/foaf/0.1/>
prefix adms: <http://www.w3.org/ns/adms#> 
prefix dct: <http://purl.org/dc/terms/>
prefix time: <http://www.w3.org/TR/owl-time/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#> 
prefix dcatno: <http://difi.no/dcatno#>  
prefix prov: <http://www.w3.org/ns/prov#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix gn: <http://www.geonames.org/ontology#>
prefix skos: <http://www.w3c.org/2004/02/skos/core#> 

construct {
    ?geoIRI a dct:Location . 
    ?geoIRI gn:name ?gn_name .
    ?geoIRI gn:officialName ?gn_officialName_no .
    ?geoIRI gn:officialName ?gn_officialName_en .
    ?geoIRI a ?gnFeatureClass .

}



WHERE {

     OPTIONAL {
        ?id :geo_uri ?geo_uri_string . # trick to replace URI
        ?id :geo_navn ?gn_name . 
        ?id :geo_navn_no ?gn_name_no .
        ?id :geo_navn_en ?gn_name_en .
        BIND(strlang(?gn_name_no, "no") as ?gn_officialName_no)
        BIND(strlang(?gn_name_en, "en") as ?gn_officialName_en)
        BIND((gn:Feature) as ?gnFeatureClass)
        BIND(iri(?geo_uri_string) as ?geoIRI)
     }
    
}
