
# Rule 7: Dataet has an identifier

prefix dcat:  <http://www.w3.org/ns/dcat#> 
prefix dct:   <http://purl.org/dc/terms/> 
SELECT ?ruleId ?ruleDescription ?resourceId ?status
WHERE 
{
      ?resourceId a dcat:Dataset .
      OPTIONAL {?resourceId dct:identifier ?identifier .}
      BIND (7 as ?ruleId) 
      BIND (("Dataset has an identifier") as ?ruleDescription) 
      BIND (BOUND(?identifier) as ?status)
}     
