package no.dcat.service;

import no.dcat.model.ApiRegistration;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.elasticsearch.annotations.Query;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.util.Optional;

@RepositoryRestResource(exported = false)
public interface ApiRegistrationRepository
    extends ElasticsearchRepository<ApiRegistration, String> {

    Page<ApiRegistration> findByCatalogId(String catalogId, Pageable pageable);

    Optional<ApiRegistration> findByIdAndCatalogId(String id, String catalogId);

    // todo there is something wrong with the autogenerated query. (0 items returned)
    // With this annotation, the query works
    @Query("{\"bool\": {\"must\": [" +
        "{\"term\":{\"catalogId\":\"?0\"}}," +
        "{\"term\":{\"apiSpecUrl\":\"?1\"}}" +
        "]}}")
    Optional<ApiRegistration> getByCatalogIdAndApiSpecUrl(String catalogId, String apiSpecUrl);

    Page<ApiRegistration> findByRegistrationStatus(String registrationStatus, Pageable pageable);

}
