# Rule 1: Catalog has one or more datasets

prefix dcat:  <http://www.w3.org/ns/dcat#> 
SELECT ?ruleId ?ruleDescription ?resourceId ?status
WHERE 
{
      {
        SELECT ?resourceId (count(?dataset) as ?count) 
        WHERE {
            ?resourceId a dcat:Catalog .
      	    OPTIONAL {?resourceId dcat:dataset ?dataset .}
        } 
        GROUP BY ?resourceId
      }
      BIND (1 as ?ruleId) 
      BIND (("Catalog has one or more datasets") as ?ruleDescription) 
      BIND ((?count>0) as ?status)
}     
