
# Rule 8: Dataet has a theme

prefix dcat:  <http://www.w3.org/ns/dcat#> 
prefix dct:   <http://purl.org/dc/terms/> 
SELECT ?ruleId ?ruleDescription ?resourceId ?status
WHERE 
{
      ?resourceId a dcat:Dataset .
      OPTIONAL {?resourceId dcat:theme ?theme .}
      BIND (8 as ?ruleId) 
      BIND (("Dataset has a theme") as ?ruleDescription) 
      BIND (BOUND(?theme) as ?status)
}     
