prefix apf: <http://jena.apache.org/ARQ/property#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dct:  <https://purl.org/dc/terms/>
prefix : <http://data.brreg.no/vocab/temp/> 
prefix foaf:  <http://xmlns.com/foaf/0.1/>
prefix adms: <http://www.w3.org/ns/adms#> 
prefix dct: <http://purl.org/dc/terms/>
prefix time: <http://www.w3.org/TR/owl-time/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#> 
prefix dcatno: <http://difi.no/dcatno#>  
prefix prov: <http://www.w3.org/ns/prov#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix gn: <http://www.geonames.org/ontology#>
prefix skos: <http://www.w3c.org/2004/02/skos/core#> 


# distribution
construct {
    ?id a dcat:Distribution .
    ?id dct:description ?description .
    ?id dct:format ?format .
    ?id dct:downloadURL ?downloadURL .
    ?id dct:license ?licenseURL .
} 
WHERE {
    ?id a :Distribution .
    
    OPTIONAL {
        ?id :beskrivelse ?beskrivelse .
        BIND(STRLANG(?beskrivelse, "nb") as ?description)
    }
    
    OPTIONAL {
        ?id :format ?form .
        BIND( ?form as ?format)
    }
    
    OPTIONAL {
        ?id :tilgangsURL ?tilgangsURL .
        BIND(IRI(?tilgangsURL) AS ?downloadURL)
    }
    
    OPTIONAL {
        ?id :lisens ?lisensURL .
        BIND(IRI(?lisensURL) as ?licenseURL)
    }

}