PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX http: <http://www.w3.org/2011/http#>
PREFIX fo: <http://www.w3.org/1999/XSL/Format#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix er: <http://data.brreg.no/meta/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix schema: <http://schema.org/>

DESCRIBE ?publisher ?dataset ?distribution ?catalog ?contact ?temporal ?spatial
WHERE {
  ?catalog a dcat:Catalog;
  dct:publisher ?publisher;
  dcat:dataset ?dataset.

  OPTIONAL {?dataset dcat:distribution ?distribution}
  OPTIONAL {?dataset dcat:contactPoint ?contact}
  OPTIONAL {?dataset dct:temporal ?temporal}
  OPTIONAL {?dataset dct:spatial ?spatial}

  FILTER (?catalog = <%s>)

}
